### ISSUE TITLE
About section: Download CV button overlapping with the paragraph of my introduction.

### ISSUE THREAD

**Issue by joydeep2001** [Nabendu-Manna/Nabendu-Manna.github.io#2]
This issue has been tested in Firefox Browser not sure about chrome. 

Reference Image:

![Screenshot from 2024-01-22 07-21-40](https://github.com/Nabendu-Manna/Nabendu-Manna.github.io/assets/70678132/a6e1a908-372a-4d53-9342-7602ad41e883)

Quick Fix: 
` <div class="about-btn">...</div>` should include the following style 
 
```css
position: absolute;
top: 100%;
transform: translateY(-200%);
```
(Tested in Firefox only)
![Screenshot from 2024-01-22 07-26-12](https://github.com/Nabendu-Manna/Nabendu-Manna.github.io/assets/70678132/646d411a-dfbe-4eb4-9598-e377018cb6ad)

**Comment by Nabendu-Manna** [comment]
Thank you 🚀
